In [1]:
import pandas as pd
import numpy as np

In [2]:
path = '/Users/thainam/Documents/GitHub/grey-model/prediction/Final/ANN_1.csv'

In [5]:
data = pd.read_csv(path)

In [6]:
data.head(20)

Unnamed: 0      True  ANN Prediction  Loss_ANN
0            0  0.055730        0.055961  0.289856
1            1  0.119399        0.118157  0.232825
2            2  0.186942        0.190385  0.184792
3            3  0.269601        0.267791  0.145387
4            4  0.359658        0.362299  0.113833
5            5  0.444127        0.465198  0.089063
6            6  0.587215        0.561702  0.069931
7            7  0.705440        0.702143  0.055472
8            8  0.805881        0.812577  0.044729
9            9  0.914992        0.906400  0.036891
10          10  1.000000        1.008321  0.031288
11          11       NaN             NaN  0.027321
12          12       NaN             NaN  0.024518
13          13       NaN             NaN  0.022511
14          14       NaN             NaN  0.021024
15          15       NaN             NaN  0.019865
16          16       NaN             NaN  0.018888
17          17       NaN             NaN  0.018018
18          18       NaN             NaN  0.017212
19          19       NaN             NaN  0.016428

In [7]:
true = data.iloc[:10, 1:2].values
print(true)

[[0.05573021]
 [0.11939919]
 [0.1869423 ]
 [0.26960084]
 [0.35965832]
 [0.44412689]
 [0.58721539]
 [0.70543965]
 [0.80588105]
 [0.91499158]]


In [24]:
pred = data.iloc[:10, 2:3].values
print(pred)

[[0.1407546 ]
 [0.19848962]
 [0.26357946]
 [0.34811112]
 [0.44309852]
 [0.5333398 ]
 [0.68213254]
 [0.8084547 ]
 [0.917213  ]
 [1.0359524 ]]


In [26]:
true = np.round(true * 37552)
print(true)

[[ 4484.]
 [ 7020.]
 [10124.]
 [13506.]
 [16678.]
 [22051.]
 [26491.]
 [30262.]
 [34360.]
 [37552.]]


In [27]:
pred = np.round(pred * 37552)
print(pred)

[[ 5286.]
 [ 7454.]
 [ 9898.]
 [13072.]
 [16639.]
 [20028.]
 [25615.]
 [30359.]
 [34443.]
 [38902.]]


In [28]:
per = pred / true
print(per)

[[1.17885816]
 [1.06182336]
 [0.97767681]
 [0.96786613]
 [0.99766159]
 [0.90825813]
 [0.96693217]
 [1.00320534]
 [1.0024156 ]
 [1.03595015]]
